# Generated by Django 4.2.6 on 2023-10-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_roleuser_user'),
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='key',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='permissionrole',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission', to='permission.permission'),
        ),
        migrations.AlterField(
            model_name='permissionrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_role', to='role.role'),
        ),
    ]
