# Generated by Django 4.2.6 on 2023-10-29 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_roleuser_user'),
        ('permission', '0002_alter_permission_key_alter_permissionrole_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrole',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='permission.permission'),
        ),
        migrations.AlterField(
            model_name='permissionrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='role.role'),
        ),
    ]
